name: Prometheus Generic Exporter Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
        default: "minor"
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 8.6.0

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Install dependencies
        run: pnpm install

      - name: Build
        id: build
        env:
          INPUT_VERSION: ${{ github.event.inputs.version }}
          # ln -s $PWD/node_modules/.pnpm $PWD/packages/agent/node_modules/.pnpm
        run: |
          npm version --commit-hooks false --git-tag-version false $INPUT_VERSION
          pnpm run build
          cd build
          pnpm install --prod
          pnpm add node-linux-x64@lts
          chmod +x prom-generic-exporter
          VERSION=$(node -e "console.log(require('./package.json').version)")
          APP_NAME=$(node -e "console.log(require('./package.json').name)")
          cd ..
          mv build ${APP_NAME}-linux-x64-${VERSION}
          chmod -R +x ${APP_NAME}-linux-x64-${VERSION}
          tar -czvf ${APP_NAME}-linux-x64-${VERSION}.tar.gz ${APP_NAME}-linux-x64-${VERSION}

          pnpm run docker \
            --tag krisboit/prom-generic-exporter:latest \
            --tag krisboit/prom-generic-exporter:${VERSION}

          docker push krisboit/prom-generic-exporter:latest
          docker push krisboit/prom-generic-exporter:${VERSION}

          echo "APP_TAG=${APP_NAME}-v${VERSION}" >> $GITHUB_ENV
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "APP_NAME=${APP_NAME}" >> $GITHUB_ENV

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Version bump
          file_pattern: package.json

      - name: Show files
        run: |
          echo "Files created"
          ls -la

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: |
            ${{ env.APP_NAME }}-linux-x64-${{ env.VERSION }}
            ${{ env.APP_NAME }}-linux-x64-${{ env.VERSION }}.tar.gz
          tag: ${{ env.APP_TAG }}
          overwrite: true
          file_glob: true
